### ISSUE TITLE
validation in pre_init fails if primary_key isn't id

### ISSUE THREAD

**Issue by jlec** [rpkilby/jsonfield#122]
```
class Foo(models.Model):
bar = models.SlugField(
    primary_key=True,
)
json = JSONField()
```

fails with

```
>>> from foo.models import Foo
>>> f = Foo()
Traceback (most recent call last):
  File "<input>", line 1, in <module>
  File "/usr/lib64/python3.4/site-packages/django/db/models/base.py", line 442, in __init__
    setattr(self, field.attname, val)
  File "/usr/lib64/python3.4/site-packages/jsonfield/subclassing.py", line 41, in __set__
    obj.__dict__[self.field.name] = self.field.pre_init(value, obj)
  File "/usr/lib64/python3.4/site-packages/jsonfield/fields.py", line 81, in pre_init
    raise ValidationError(_("Enter valid JSON"))
django.core.exceptions.ValidationError: ['Enter valid JSON']
```

**Comment by chokosabe** [comment]
Voting this up. Having the same issue....

**Comment by gjcarneiro** [comment]
Same here.  This is affecting gargoyle-yplan, which has a model like this:
```python
class Switch(models.Model):
    ...
    key = models.CharField(max_length=64, primary_key=True)
    value = JSONField()
    label = models.CharField(max_length=64, null=True)
    date_created = models.DateTimeField(default=now)
    date_modified = models.DateTimeField(auto_now=True)
    description = models.TextField(null=True)
    status = models.PositiveSmallIntegerField(default=DISABLED, choices=STATUS_CHOICES)
```
