### ISSUE TITLE
KeyError while accessing deferred field

### ISSUE THREAD

**Issue by uvarenkovserf** [rpkilby/jsonfield#198]
Create class:
```
import jsonfield
from django.db import models


class TestClass(models.Model):
    test_field = jsonfield.JSONField()
```
Then in shell:
```
>>> TestClass.objects.create(test_field={'a': 'b'})
<TestClass: TestClass object>
>>> TestClass.objects.first().test_field
{u'a': u'b'}
>>> TestClass.objects.defer('test_field').first().test_field
Traceback (most recent call last):
  File "<console>", line 1, in <module>
  File "/home/vitar/Downloads/test/venv/local/lib/python2.7/site-packages/jsonfield/subclassing.py", line 36, in __get__
    return obj.__dict__[self.field.name]
KeyError: 'test_field'
```
I have a feeling that changes in this patch https://github.com/django/django/pull/6118 are not taken into account. I may be wrong though.

**Comment by ezheidtmann** [comment]
I'm also encountering this bug. Is there any guidance from the Django project on how to achieve compatibility?
