### ISSUE TITLE
Can not store ordinary Python strings in JSONfield

### ISSUE THREAD

**Issue by jrief** [rpkilby/jsonfield#33]
Since version 0.9.4 I am not able to store ordinary Python strings in a JSONfield. Up to version 0.9.2 this worked without problems.
Did I miss something? From my point of view, it should not matter, if I store ordinary strings, lists or dicts in a JSONfield.

**Comment by dogada** [comment]
Strings again can't be saved with JSONField. With Django 1.7.4 I get:
```
>>> e1.value = unicode("xyz")
Traceback (most recent call last):
  File "<console>", line 1, in <module>
  File "/usr/local/lib/python2.7/dist-packages/django/db/models/fields/subclassing.py", line 37, in __set__
    obj.__dict__[self.field.name] = self.field.to_python(value)
  File "/usr/local/lib/python2.7/dist-packages/jsonfield/fields.py", line 101, in to_python
    raise ValidationError(msg)
ValidationError: [u"'xyz' is not a valid JSON string."]
```

**Comment by pedroteixeira** [comment]
:+1: didn't work for me either
